services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Tilastot\:
    resource: ../src/Tilastot
    exclude: ../src/Tilastot/{Entity,Migrations,Model,Resources,Tests,Widget}

  App\Tilastot\Utils\:
    resource: ../src/Tilastot/Utils
    public: true

  App\Tilastot\Module\ScheduleModule:
    tags:
      - name: contao.frontend_module
        category: texts
        template: mod_schedule
        renderer: esi
        type: schedule
