services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  App\Tilastot\:
    resource: ../src/Tilastot
    exclude: ../src/Tilastot/{Entity,Migrations,Model,Resources,Tests,Widget}

  App\Tilastot\Utils\:
    resource: ../src/Tilastot/Utils
    public: true

  App\Tilastot\Cron\getLatestProductsCron:
    arguments:
      - "%woo_key%"
      - "%woo_secret%"

  App\Tilastot\EventListener\LoadFormFieldListener:
    tags:
      - { name: contao.hook, hook: LoadFormFieldListener }

  App\Tilastot\Module\ScheduleModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_schedule
        type: schedule
  App\Tilastot\Module\NextGameModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_nextgame
        type: nextgame
  App\Tilastot\Module\StandingsModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_standings
        type: standings
  App\Tilastot\Module\RosterModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_roster
        type: roster
  App\Tilastot\Module\PlayerModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_player
        type: player
  App\Tilastot\Module\PartnersModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_partners
        type: partners
  App\Tilastot\ContentElement\WrapperBlockStart:
    tags:
      - name: contao.content_element
        category: grid
        template: wrapper_block_start
        type: rowStart
  App\Tilastot\ContentElement\WrapperBlockEnd:
    tags:
      - name: contao.content_element
        category: grid
        template: wrapper_block_end
        type: rowEnd
