services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Tilastot\:
    resource: ../src/Tilastot
    exclude: ../src/Tilastot/{Entity,Migrations,Model,Resources,Tests,Widget}

  App\Tilastot\Utils\:
    resource: ../src/Tilastot/Utils
    public: true

  App\Tilastot\Module\ScheduleModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_schedule
        renderer: esi
        type: schedule
  App\Tilastot\Module\NextGameModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_nextgame
        renderer: esi
        type: nextgame
  App\Tilastot\Module\StandingsModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_standings
        renderer: esi
        type: standings
  App\Tilastot\Module\RosterModule:
    tags:
      - name: contao.frontend_module
        category: tilastot
        template: mod_roster
        renderer: esi
        type: roster
  App\Tilastot\ContentElement\WrapperBlockStart:
    tags:
      - name: contao.content_element
        category: grid
        template: wrapper_block_start
        type: rowStart
  App\Tilastot\ContentElement\WrapperBlockEnd:
    tags:
      - name: contao.content_element
        category: grid
        template: wrapper_block_end
        type: rowEnd
